apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx22
  labels:
    app: nginx22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx22
  template:
    metadata:
      labels:
        app: nginx22
    spec:
      containers:
      - name: nginx22
        image: ghcr.io/dmitriy-malevich/tasks32:1.0.1
        livenessProbe:
          httpGet:
            path: index.html
            port: 80
            httpHeaders:
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30
          periodSeconds: 10
            # ports:
            # - containerPort: 80
        volumeMounts:
          - name: nginx-index-file22
            mountPath: /home/tasks4/index.html
            subPath: index.html

          - name: nginx-secret22
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-index-file22
          configMap:
           name: nginx-configmap22

        - name: nginx-secret22
          secret:
            secretName: nginx-secret22


---

apiVersion: v1
kind: Service
metadata:
  name: my-service-cm22
spec:
  type: NodePort
  selector:
    app: nginx22
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30089       


